### ISSUE TITLE
Discrete switch for the fill aesthetic?

### ISSUE THREAD

**Issue by adibender** [wilkelab/ggridges#1]
Hi, 

is it possible that the fill color *discretely* changes depending on `x`? 
For example if x > 50, then fill = yellow, otherwise fill=blue.

**Comment by clauswilke** [comment]
Yes, this is possible, using the `_gradient ` versions of the geoms.

**Comment by adibender** [comment]
I'll leave this here in case somebody is looking: https://gist.github.com/adibender/28041453a2a8c3e42c09484a55668d55
