### ISSUE TITLE
Plotting point shapes / colors by variable?

### ISSUE THREAD

**Issue by heinonmatti** [wilkelab/ggridges#16]
Hi, 

There probably is an obvious solution to this, but I'm a bit naive with plotting, still. I'd like to have point_shape and point_fill defined manually to indicate e.g. gender groups. How would I go about doing this? 

Many thanks!

Matti

**Comment by clauswilke** [comment]
Github issues are not the place to ask for user support. You can consider asking on Stackoverflow.

**Comment by heinonmatti** [comment]
Thanks. I [did so](
https://stackoverflow.com/questions/49581235/plotting-ggridges-point-shapes-colors-by-variable) and was suggested to do a feature request. Apologies for not knowing the etiquette, wanted to ask if that's something you'd prefer I do, or not?

**Comment by clauswilke** [comment]
In case of doubt, always ask on stackoverflow first. If the conversation there seems to indicate that it's a valid bug or feature request, then open an issue on github and refer to the conversation on stackoverflow. In this particular case, you didn't even provide a reproducible example, so I wasn't even exactly sure what the question was.
