### ISSUE TITLE
Alpha only controls ridge fill, not ridge color.

### ISSUE THREAD

**Issue by mir-cat** [wilkelab/ggridges#2]
Using the example from the README:

```
ggplot(diamonds, aes(x = price, y = cut)) +
    geom_density_ridges(scale = 2) + theme_ridges() +
    scale_y_discrete(expand = c(0.01, 0)) +   # will generally have to set the `expand` option
    scale_x_continuous(expand = c(0, 0))  
```
![image](https://user-images.githubusercontent.com/10320217/30827942-e440362e-a209-11e7-9bfb-3baf6e93cc17.png)

```

ggplot(diamonds, aes(x = price, y = cut)) +
    geom_density_ridges(scale = 2, alpha = 0.1) + theme_ridges() +
    scale_y_discrete(expand = c(0.01, 0)) +   # will generally have to set the `expand` option
    scale_x_continuous(expand = c(0, 0))  
```

![image](https://user-images.githubusercontent.com/10320217/30827933-de89e6ee-a209-11e7-8677-871feaa6ca32.png)

In the help it says that alpha controls 'Transparency level of color and fill'. Right now it only seems to cover fill, as the outline remains unchanged with alpha.

Using `ggridges` version 0.4.1 on OSX

**Comment by clauswilke** [comment]
Yes, this is correct. The documentation is wrong. In general in ggplot2, for objects that have fill and color, alpha is only applied to fill. It's the same behavior as in `geom_density()`, for example.

If you absolutely want transparency on the lines, you can manually set a color that has the transparency you want:

```
ggplot(diamonds, aes(x = price, y = cut)) +
  # manually set color to black with 0.1 alpha (hex #0000001A)
  geom_density_ridges(scale = 2, alpha = 0.1, color = "#0000001A") + theme_ridges() +
  scale_y_discrete(expand = c(0.01, 0)) +   # will generally have to set the `expand` option
  scale_x_continuous(expand = c(0, 0))  
```
<img width="723" alt="screen shot 2017-09-25 at 3 10 38 pm" src="https://user-images.githubusercontent.com/4210929/30828586-bf4bf34a-a203-11e7-8227-ee7731d48caf.png">

Not sure how useful that is, though.

**Comment by clauswilke** [comment]
You can also use colors with transparency in `scale_color_manual()` if you want multiple different colors all with transparency.

**Comment by mir-cat** [comment]
Thanks! This solves my issue.

**Comment by clauswilke** [comment]
Reopening issue to flag that documentation needs to be fixed.
