### ISSUE TITLE
Problems shading area under ggridges histogram (stat = binline)?

### ISSUE THREAD

**Issue by ixodid198** [wilkelab/ggridges#20]
With help from Maurits Evers I was able to shade part of the area under a density plot. 
See [here](https://stackoverflow.com/questions/49961582/how-shade-area-under-ggridges-curve/49962274?noredirect=1#comment86996420_49962274).

However, when I attempt this same technique with a histogram the shading is wonky. Please see [here](https://stackoverflow.com/questions/49992547/how-shade-area-under-ggridges-histogram-stat-binline?noredirect=1#comment87004840_49992547).

**Comment by clauswilke** [comment]
Not a bug. See my answer on Stackoverflow.
