### ISSUE TITLE
Feature suggestion: directed cyclical scales

### ISSUE THREAD

**Issue by brianwdavis** [wilkelab/ggridges#3]
I've been working on this idea for a bit, so when I saw your alternating/cycling scales, I thought it was a good match.

Say you have some categorical axis that has an inherent order, but you also want to be able to distinguish neighbors. You need a color/fill palette that is directed (e.g. `scales::colour_ramp` or `viridis::viridis_pal`), but then you need to choose values that are a maximum perceptual distance from one another (as in `scales::hue_pal`), and then order them by alternating among neighbors. Currently the implementation of `cyclical_scale` only does the alternating-neighbors bit.

![image](https://user-images.githubusercontent.com/13338560/30843121-1f772c16-a255-11e7-8bab-55c75db61efe.png)

I'd like to suggest a `scale_cycle_along`. Given a vector of ordinal colors, `cycle_along` will group them into an arbitrary number of buckets, then select them out in order of position within bucket along buckets. E.g.:

![image](https://user-images.githubusercontent.com/13338560/30843316-3f07a99c-a256-11e7-8742-ab6d3e074e66.png)

Cycled along 10 points with 2 buckets.

![image](https://user-images.githubusercontent.com/13338560/30843357-9b099c3c-a256-11e7-9bc8-c53618a2b8ee.png)

Cycled along 10 points with 3 buckets.

Obviously it works better with "simple" gradients, like the color ramp or viridis. Here's an example of how it might be used:

```
ggplot(diamonds, aes(price/carat, clarity, fill = clarity)) + 
  theme_ridges(font_size = 10) +
  geom_density_ridges() + 
  scale_fill_cycle_along(option = "C", begin = 0.1, end = 0.9) +
  scale_x_log10(breaks = outer(1:5, 10^(3:4)))
```

![image](https://user-images.githubusercontent.com/13338560/30843379-cf6c8908-a256-11e7-81c9-63cb04799a9c.png)

This way you can immediately see that there's a hierarchy to **clarity**, but it's also still easy to distinguish each neighbor from the next.

```
library(tidyr)
library(dplyr)

data_frame(x = -15:15) %>% 
  group_by(x) %>% 
  mutate(y = list(rnorm(20, mean = 0.01*x^2 - 0.1*x))) %>% 
  unnest() %>% 
  ggplot(aes(y, factor(x), fill = factor(x))) + 
  geom_density_ridges() +
  theme_ridges(font_size = 10) +
  scale_fill_cycle_along(cycle_by = 3)
```

![image](https://user-images.githubusercontent.com/13338560/30843542-d51491d8-a257-11e7-823b-d8de3661309c.png)

Likewise with this figure, but demo'd with 3 buckets to `cycle_by`.

My original use case was for segments along paths, so you could see the passage of time while still seeing where each discrete segment started and stopped. I think that `ggridges` might also benefit.

```
cycle_along <- function(vector, cycle_by = 2L) {
  
  if (is.list(vector)) {vector <- unlist(vector)}
  stopifnot(is.vector(vector))
  
  n <- length(vector)
  stopifnot(n >= cycle_by)
  
  grps <- rep_len(1:cycle_by, n)
  unsplit(split(vector, sort(grps)), grps)
  
}


cycle_along_pal <- function(f, cycle_by = 2, ...){
  function(n) {
    hues <- f(...)(n)
    cycle_along(hues, cycle_by)
  }
}


scale_fill_cycle_along <- function(f = viridis::viridis_pal, alpha = 1, direction = 1, cycle_by = 2, guide = "none", ...) {
  discrete_scale("fill", "cycled_along", guide = guide,
                 palette = cycle_along_pal(f, cycle_by = cycle_by, alpha = alpha, direction = direction, ...))
}

scale_colour_cycle_along <- function(f = viridis::viridis_pal, alpha = 1, direction = 1, cycle_by = 2, guide = "none", ...) {
  discrete_scale("colour", "cycled_along", guide = guide,
                 palette = cycle_along_pal(f, cycle_by = cycle_by, alpha = alpha, direction = direction, ...))
}

```

**Comment by clauswilke** [comment]
You can submit a pull request.

A couple of comments:

- I only accept pull requests if the feature is properly documented.
- Your function takes two arguments (`alpha` and `direction`) that are defined for viridis but wouldn't necessarily be defined for another palette function. I'm also not overly excited about the virids palette and would probably not accept it as default. The function `sequential_hcl` from colorspace would be a better option. A new version of colorspace will come out relatively soon with much improved options for `sequential_hcl`. In either case, you'll have to solve the issue of how to customize the palette function in a generic way.

**Comment by clauswilke** [comment]
Or maybe better, take a vector of color values rather than a palette function as argument, just like `scale_*_cyclical`.
