### ISSUE TITLE
unexpected behaviour when combining ggridges with other geoms

### ISSUE THREAD

**Issue by mkoohafkan** [wilkelab/ggridges#32]
I'm running into some weird behaviors when trying to annotate a `ggridges` plot with simple geoms like `geom_rect`. I have three examples that illustrate some of this behavior:

**example 1: alpha of `geom_rect` not interpreted correctly**
```
library(ggplot2)
library(ggridges)
ggplot(mtcars) +
  geom_rect(xmin = 10, xmax = 20, ymin = -Inf, ymax = Inf,
  alpha = 0.1, fill = "red") +
  geom_density_ridges2(aes(x = mpg, fill = cyl, y = cyl, group = cyl))
```
**example 2:  alpha of `geom_rect` is specified as constant, but changes across facets**
```
ggplot(mtcars) +
  geom_rect(xmin = 10, xmax = 20, ymin = -Inf, ymax = Inf,
  alpha = 0.1, fill = "red") +
  geom_density_ridges2(aes(x = mpg, fill = cyl, y = cyl, group = cyl)) +
  facet_wrap(~gear)
```
**example 3: manipulation of aesthetics (e.g. using `factor`) cause problems in additional geoms**
```
ggplot(mtcars) +
  geom_vline(xintercept = 15, linetype = "dashed") +
  geom_density_ridges2(aes(x = mpg, fill = cyl, y = cyl, group = cyl)) +
  facet_wrap(~factor(gear, levels = rev(sort(unique(gear)))))
## Error in factor(gear, levels = rev(sort(unique(gear)))) : 
##   object 'gear' not found
```

My first guess is that the issue is related to how aesthetics specifications are shared or accessed when a `ggridges` geom is used.

**Comment by clauswilke** [comment]
None of these are issues with ggridges. The first two are a misunderstanding of how ggplot2 works (the geoms inherit the data, hence you're drawing the rectangle multiple times) and the last is possibly a bug in `facet_wrap()` (that may have been reported already; you should check the issues).

``` r
library(ggplot2)
library(ggridges)
#> 
#> Attaching package: 'ggridges'
#> The following object is masked from 'package:ggplot2':
#> 
#>     scale_discrete_manual
ggplot(mtcars) +
  geom_rect(data = data.frame(x = 1),
            xmin = 10, xmax = 20, ymin = -Inf, ymax = Inf,
            alpha = 0.1, fill = "red") +
  geom_density_ridges2(aes(x = mpg, fill = cyl, y = cyl, group = cyl))
#> Picking joint bandwidth of 1.38
```

![](https://i.imgur.com/9dyjWd2.png)

``` r

ggplot(mtcars) +
  geom_rect(data = data.frame(x = 1),
            xmin = 10, xmax = 20, ymin = -Inf, ymax = Inf,
            alpha = 0.1, fill = "red") +
  geom_density_ridges2(aes(x = mpg, fill = cyl, y = cyl, group = cyl)) +
  facet_wrap(~gear)
#> Picking joint bandwidth of 1.01
#> Picking joint bandwidth of 1.96
#> Picking joint bandwidth of 0.76
#> Warning in FUN(X[[i]], ...): no non-missing arguments to max; returning -
#> Inf
```

![](https://i.imgur.com/Sn6GNoT.png)

``` r

# doesn't work (bug in facet_wrap()?)
ggplot(mtcars) +
  geom_vline(xintercept = 15, linetype = "dashed") +
  geom_point(aes(x = mpg, fill = cyl, y = cyl, group = cyl)) +
  facet_wrap(~factor(gear, levels = rev(sort(unique(gear)))))
#> Error in factor(gear, levels = rev(sort(unique(gear)))): object 'gear' not found

# works
ggplot(mtcars) +
  #geom_vline(xintercept = 15, linetype = "dashed") +
  geom_point(aes(x = mpg, fill = cyl, y = cyl, group = cyl)) +
  facet_wrap(~factor(gear, levels = rev(sort(unique(gear)))))
```

![](https://i.imgur.com/sx9BMey.png)

<sup>Created on 2019-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mkoohafkan** [comment]
OK thanks---interesting that using `data = NULL` didn't do the trick for the first two examples (I tried that but didn't think to use a fake dataset).

**Comment by clauswilke** [comment]
The correct way to do it would be to put your `xmin`, `xmax`, `ymin`, and `ymax` into a dataset and then use `aes()` to map the data onto aesthetics. But the method I showed here works the same.
