### ISSUE TITLE
Jittered Points = TRUE is ignored when using stat = "density"

### ISSUE THREAD

**Issue by dylanjm** [wilkelab/ggridges#37]
Hi, I was interested in creating a rug-plot for some data I have and was confused after following the vignette about how to do so. I realized that because I am using `stat = "density"` that `geom_density_ridges()` is ignoring `jittered_points = TRUE`. I figured I would report an issue in case this was a bug. Here is a reprex using `iris`

``` r
library(ggplot2)
library(ggridges)
#> 
#> Attaching package: 'ggridges'
#> The following object is masked from 'package:ggplot2':
#> 
#>     scale_discrete_manual

ggplot(iris, aes(x=Sepal.Length, y=Species)) +
    geom_density_ridges2(
                         jittered_points = TRUE,
                         position = position_points_jitter(width = 0.05, height = 0),
                         point_shape = '|', point_size = 3, point_alpha = 1, alpha = 0.7,
    )
#> Picking joint bandwidth of 0.181
```

![](https://i.imgur.com/ZU9lfxA.png)

``` r

ggplot(iris, aes(x=Sepal.Length, y=Species, height = ..density..)) +
    geom_density_ridges2(stat = "density",
        jittered_points = TRUE,
        position = position_points_jitter(width = 0.05, height = 0),
        point_shape = '|', point_size = 3, point_alpha = 1, alpha = 0.7,
    )
#> Warning: Ignoring unknown parameters: jittered_points
```

![](https://i.imgur.com/XiVaYy5.png)

<sup>Created on 2019-06-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I am very interested in using both a rug-plot and computing `stat = "density"` as this graphic is for management who will ask questions about the kernal density showing values that are not possible (i.e. values < 0), I want to remain brief and not get in the weeds of what a kernal density is actually computing.

**Comment by clauswilke** [comment]
The jittered points feature needs to be supported by the stat. Regular `stat_density()` doesn't do that.

You can cut off the x axis range of the densities to avoid negative numbers.

``` r
library(ggplot2)
library(ggridges)
#> 
#> Attaching package: 'ggridges'
#> The following object is masked from 'package:ggplot2':
#> 
#>     scale_discrete_manual

ggplot(iris, aes(x=Sepal.Length, y=Species)) +
  geom_density_ridges2(
    jittered_points = TRUE,
    position = position_points_jitter(width = 0.05, height = 0),
    point_shape = '|', point_size = 3, point_alpha = 1, alpha = 0.7,
    from = min(iris$Sepal.Length), to = max(iris$Sepal.Length)
  )
#> Picking joint bandwidth of 0.181
```

![](https://i.imgur.com/Mu4qezM.png)

<sup>Created on 2019-06-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
