### ISSUE TITLE
Adding package to conda-forge

### ISSUE THREAD

**Issue by dhimmel** [wilkelab/ggridges#6]
Would be great to be able to specify `ggridges` in a conda `environment.yml`. I know building conda packages can be kind of a pain, but it make using the package (at a specific version) easier.

My understanding is that this process would start with a pull request to https://github.com/conda-forge/staged-recipes. I don't have time for this now, but perhaps would consider it in a few months, if I start using Ridgeline Plots frequently.

**Comment by clauswilke** [comment]
Does anybody actually use conda with R? What's wrong with `install.packages()`?

I'm not opposed to this, it's just not very high on my own priority list.

**Comment by dhimmel** [comment]
> Does anybody actually use conda with R?

I do! It solves many prickly problems like environments with both Python and R and versioned R environments. Most popular R packages have been built for `conda-forge`... demonstrating people are using it (otherwise they wouldn't put in the effort). For example, even `cowplot` [is on](https://github.com/conda-forge/r-cowplot-feedstock) conda-forge.

> I'm not opposed to this, it's just not very high on my own priority list.

Makes sense given priorities. Also given that the repo is openly licensed, it wouldn't matter whether you were opposed it (the beauty of open source) :wink:. I'll take a deeper look when I have time.

**Comment by clauswilke** [comment]
> For example, even cowplot is on conda-forge.

Maybe the solution then is to have cowplot auto-import ggridges. :-)

In any case, I've been thinking about breaking cowplot into separate, more focused packages and then turn cowplot a meta-package, like tidyverse, so this may make sense at some point.

**Comment by clauswilke** [comment]
Closing this, as ggridges seems to be on conda-forge by now.
