### ISSUE TITLE
Outlier bins for histogram?

### ISSUE THREAD

**Issue by jinkim3** [wilkelab/ggridges#66]
Issues are meant to report bugs or request features. If you have questions about how to correctly use this package, please don't use the issue system. Such questions can be asked on stackoverflow https://stackoverflow.com/ or the RStudio community https://community.rstudio.com/. If you are not sure where to go, please try https://stackoverflow.com/ first.

Issues must contain reproducible code examples. Please use the reprex package to create your example (see here: http://reprex.tidyverse.org/). Issues without reprex may be closed without comment.

Please delete these instructions after you have read them.

------

Dear Prof. Wilke,

Could you consider adding a function or option for adding outlier bins for the histograms in the example below, so that users can manually set cutoff values for the bins at either extreme?

```{r}
ggplot(iris, aes(x = Sepal.Length, y = Species, height = stat(density))) + 
  geom_density_ridges(stat = "binline", bins = 20, scale = 0.95, draw_baseline = FALSE)
```

**Comment by modche** [comment]
I dont understand the issue here?
![image](https://user-images.githubusercontent.com/13642619/105010614-3e9dd200-5a3c-11eb-990a-852536914bc7.png)

**Comment by jinkim3** [comment]
I didn't find any issue; I was just requesting a new feature. If it's not worth the effort, please ignore my request. Thank you!

**Comment by modche** [comment]
> I didn't find any issue; I was just requesting a new feature. If it's not worth the effort, please ignore my request. Thank you!

Sorry. I am not the maintainer of this package. And: I do not force you to close this thread but I am do not understand your "feature request".
