### ISSUE TITLE
Top of upper density clipped

### ISSUE THREAD

**Issue by hummuscience** [wilkelab/ggridges#68]
I noticed this happening on multiple occasion, it is even visible in the vignette (https://wilkelab.org/ggridges/articles/introduction.html) [this for example.](https://wilkelab.org/ggridges/articles/introduction_files/figure-html/unnamed-chunk-5-1.png)

I tried multiple ways of producing the plots, it all leads to this same issue.

Currently, I am dealing with it by using `expand_limits` from ggplot but I guess there is an easy fix for that...

**Comment by clauswilke** [comment]
It's in the documentation:
https://wilkelab.org/ggridges/articles/introduction.html#themes-1
