### ISSUE TITLE
request: cran submission?

### ISSUE THREAD

**Issue by tanho63** [wilkelab/ggridges#87]
Hi! I've been working on a package which depends on ggridges, and have noticed a good deal of ggplot2 deprecation warnings which seem to have been resolved in #80. Is it possible to release the current GH version to CRAN to help clean up R CMD checks?

**Comment by clauswilke** [comment]
Yes, I know, I need to do that. Will see if I can take care of it next week.

**Comment by clauswilke** [comment]
It's now on CRAN. Apologies for the delay.
