### ISSUE TITLE
Implement draw_quantiles like in geom_violin

### ISSUE THREAD

**Issue by adrfantini** [wilkelab/ggridges#9]
Title says it all, really.
It'd be nice to be able to draw vertical quantiles, just like the quantiles that can be drawn by `ggplot`'s `geom_violin()` using the option `draw_quantiles`

**Comment by clauswilke** [comment]
I'll probably have to add this feature at some point. It's frequently requested. In the meantime, note that you can color by quantiles. (Transparency is tricky in this case and needs to be specified in the hex codes for the colors).
```
ggplot(iris, aes(x=Sepal.Length, y=Species, fill=factor(..quantile..))) +
    geom_density_ridges_gradient(calc_ecdf = TRUE, quantiles = c(0.05, 0.95)) +
    scale_fill_manual(name = "Probability\nranges",
                      values = c("#FF0000A0", "#A0A0A0A0", "#0000FFA0")) +
    theme_ridges() + scale_y_discrete(expand = c(0.01, 0))
```
<img width="657" alt="screen shot 2017-11-16 at 12 02 41 am" src="https://user-images.githubusercontent.com/4210929/32876235-886d5068-ca61-11e7-89b8-12eee5427f44.png">

**Comment by adrfantini** [comment]
Oooh, this is nice. Could this be added to the examples vignette and/or to the manual? This can definitely be extremely useful.

**Comment by clauswilke** [comment]
It's in the documentation for `stat_density_ridges()` but probably needs to be featured more prominently or in a different location.

**Comment by clauswilke** [comment]
Drawing quantile lines is now possible.
```
ggplot(iris, aes(x=Sepal.Length, y=Species)) +
  geom_density_ridges(quantile_lines = TRUE, quantiles = c(0.25, 0.5, 0.75)) +
  scale_y_discrete(expand = c(0.01, 0)) +
  theme_ridges(grid = FALSE, center = TRUE)
```
<img width="526" alt="screen shot 2017-11-18 at 3 35 35 pm" src="https://user-images.githubusercontent.com/4210929/32985013-3b686e1c-cc76-11e7-8b27-002ad14ac0e9.png">

**Comment by adrfantini** [comment]
Thanks for the excellent work.

Adriano Fantini

2017-11-18 22:37 GMT+01:00 Claus Wilke <notifications@github.com>:
