### ISSUE TITLE
Support `grid::pattern()` / gradient fills

### ISSUE THREAD

**Issue by trevorld** [wilkelab/ggridges#94]
`{ggplot2}` 3.5.0 geoms were updated to accept `grid.pattern()` / gradient fills.  The geoms in `{ggridges}` could also be updated to accept such fills:

* [x] Bump required ggplot2 version number to v3.5
* [x] Replace code like `fill = alpha(data$fill, data$alpha)` with `fill = ggplot2::fill_alpha(data$fill, data$alpha)`

**Comment by clauswilke** [comment]
You're welcome to prepare a PR.
